sonar.projectKey=awb-app
sonar.projectName=AWB Application
sonar.projectVersion=1.0

sonar.sources=backend/app,frontend/src
sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/*.test.js,**/*.test.jsx,**/dist/**,**/build/**,**/.venv/**

sonar.python.version=3.12
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.python.coverage.reportPaths=reports/quality/backend-coverage.xml
sonar.sourceEncoding=UTF-8
